### ISSUE TITLE
AttributeError: module 'select' has no attribute 'epoll'

### ISSUE THREAD

**Issue by wojtek-fliposports** [dsoprea/PyInotify#36]
```python
  File "/usr/local/lib/python3.6/site-packages/inotify/adapters.py", line 44, in __init__
    self.__epoll = select.epoll()
AttributeError: module 'select' has no attribute 'epoll'
```
and `select` from:
```
<module 'select' from '/tmp/tmp36/lib/python3.6/lib-dynload/select.cpython-36m-darwin.so'>
```

**Comment by wojtek-fliposports** [comment]
it.s under OSX.. sorry.. close or maybe add wrong platform exception

**Comment by dsoprea** [comment]
Interesting. Our unit-tests stop at 3.5 so we missed this. Can you investigate?

**Comment by wojtek-fliposports** [comment]
I was trying to run gunicorn under docker linux image on Darwin platform (OSX), gunicorn with --reload feature

**Comment by jcea** [comment]
"epoll" is linux only. I have a patch to use "selectors" module when using Python >=3.4. This way this library run under SmartOS (a Solaris derivative).

filesystem notifications are highly unportable. MacOS X will surely provide a similar interface but the details are most probably different. In my case, SmartOS provides a linux inotify compatibility layer beside their native filesystem notification, so I can use this library with a half a dozen of line changes.

@dsoprea , are you interested in my patches?. Currently they only work on Python >=3.4, but I could do a Python 2 compatible version.

**Comment by rkmrHonjo** [comment]
Excuse me,

I used this library on Linux & python3.5, but same error was occurred...
Are there other required packages?
And, are there any samples about epoll?

**Comment by rkmrHonjo** [comment]
Really sorry, my above comment was caused by my code...
Please ignore it.

**Comment by dsoprea** [comment]
Patches are welcome.

**Comment by huzunhao** [comment]
@jcea  Could you share your patch?
